version: '3.8'

name: event-sourcing-backbone
services:
  redis:
    image: redis:6.2-alpine
    # image: redis:6.2
    container_name: redis
  
    restart: always
    ports:
      - 6379:6379
    # command: redis-server --save 20 1 --loglevel warning --requirepass YOUR_PASS
    command: redis-server --loglevel warning 
    volumes: 
      - redis:/data

  # #  https://redis.io/docs/install/install-stack/docker/
  # redis-stack:
  #   image: redis/redis-stack:latest
  #   container_name: redis-stack
  #   restart: always
  #   ports:
  #     - 6379:6379
  #     - 8001:8001
  #   # command: redis-server --save 20 1 --loglevel warning 
  #   command: redis-server --loglevel warning 
  #   # command: redis-server --loglevel warning  --requirepass YOUR_PASS
  #   volumes: 
  #     - redis:/data

  #localstack:
  #  image: localstack/localstack
  #  container_name: localstack
  #  environment:
  #    SERVICES: s3
  #    # SERVICES: firehose,kinesis,lambda,s3,sqs,dynamodb
  #    AWS_DEFAULT_REGION: us-east-1
  #    # EDGE_PORT: 4566
  #  ports:
  #    - 4566:4566 # LocalStack endpoint
  #    - 4510-4559:4510-4559 # external services port range
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #    - localstack:/tmp/localstack/data

  # https://docs.localstack.cloud/getting-started/installation/#docker-compose
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - 4566:4566            # LocalStack Gateway
      # - 4510-4559:4510-4559  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      SERVICES: s3
      # SERVICES: firehose,kinesis,lambda,s3,sqs,dynamodb
      AWS_DEFAULT_REGION: us-east-1
      DEBUG: ${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  redis:
    driver: local
  localstack:
    