name: .NET Build & Publish NuGet V1
  
on:
  push:
    branches: [ master ]
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:

    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Weknow.EventSource.Backbone.Contracts /property:Configuration=Debug 
          
    - name: Build & generate NuGet package
      run: | 
        run: dotnet build Weknow.EventSource.Backbone.Contracts -c Debug --no-restore
        dotnet pack Weknow.EventSource.Backbone.Contracts -c Debug -o out --no-restore
      
    - name: Add NuGet Source
      run: dotnet nuget add source --username Bnayae --password ${{ secrets.NUGET_API_EVENT_SOURCE_KEY }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Bnayae/index.json"

    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./Weknow.EventSource.Backbone.Contracts/out/*.nupkg --skip-duplicate --no-symbols true --no-restore
