name: Deploy
  
on:
  workflow_run:
    workflows: ["Prepare"]
    types:
      - completed

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'

    
env: # https://docs.github.com/en/actions/learn-github-actions/environment-variables
  BUILD_CONFIG: Release
  DOTNET_VER: 7.0.x
  INCLUDE_PRERELEASE: false
  
jobs:
  build:

    name: build
    runs-on: ubuntu-latest

    services:
      mssql:
        image: redislabs/rejson:latest
        # env:
        #   PASSWORD: ${{ secrets.NUGET_PUBLISH }}
        ports:
          - 6379:6379
      localstack:
        image: localstack/localstack
        env:
          SERVICES: s3
          DEFAULT_REGION: us-east-1
          DATA_DIR: /tmp/localstack/data
        ports: ["4566:4566"]
  
    # env:
    #   REDIS_EVENT_SOURCE_ENDPOINT: localhost:6379
    #   S3_EVENT_SOURCE_REGION: us-east-1
    #   S3_EVENT_SOURCE_BUCKET: event-sourcing-demo
    #   S3_EVENT_SOURCE_ACCESS_KEY: localstack
    #   S3_EVENT_SOURCE_SECRET: localstack

    steps:
    - uses: actions/checkout@v2 
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VER }}
        include-prerelease: ${{ env.INCLUDE_PRERELEASE }}
        
    - name: Restore dependencies
      run: dotnet restore /property:Configuration=${{ env.BUILD_CONFIG }}
    - name: Build
      run: dotnet build  --configuration ${{ env.BUILD_CONFIG }} --no-restore 

    - name: Unit Test
      run: dotnet test Tests/EventSourcing.Backbone.UnitTests --configuration ${{ env.BUILD_CONFIG }} --no-restore --no-build --verbosity normal 

    - name: Integration Test Redis
      env:
        REDIS_EVENT_SOURCE_ENDPOINT: localhost:6379
      run: dotnet test Tests/EventSourcing.Backbone.IntegrationTests --configuration ${{ env.BUILD_CONFIG }} --no-restore --no-build --verbosity normal --filter provider!=s3

    - name: Configure localstack
      run: |
        aws configure set aws_access_key_id localstack
        aws configure set aws_secret_access_key localstack
        aws configure set default.region us-east-1
        aws mb s3://event-sourcing-demo --endpoint-url=http://localhost:4566

    - name: Integration Test S3
      run: dotnet test Tests/EventSourcing.Backbone.IntegrationTests --configuration ${{ env.BUILD_CONFIG }} --no-restore --no-build --verbosity normal --filter provider=s3

    - name: Push generated package to GitHub registry
      env:
        REDIS_EVENT_SOURCE_ENDPOINT: localhost:6379
        S3_EVENT_SOURCE_REGION: us-east-1
        S3_EVENT_SOURCE_BUCKET: event-sourcing-demo
        S3_EVENT_SOURCE_ACCESS_KEY: localstack
        S3_EVENT_SOURCE_SECRET: localstack
      run: dotnet nuget push ./**/*.nupkg -k ${{ secrets.NUGET_PUBLISH }} -s https://api.nuget.org/v3/index.json --skip-duplicate 

  src-gen:

    name: src-gen
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VER }}
        include-prerelease: ${{ env.INCLUDE_PRERELEASE }}

    - name: Restore dependencies
      run: dotnet restore /property:Configuration=Gen
    - name: Build
      run: dotnet build  --configuration Gen --no-restore 

    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./**/*.nupkg -k ${{ secrets.NUGET_PUBLISH }} -s https://api.nuget.org/v3/index.json --skip-duplicate
